_target_: uni2ts.data.builder.simple.generate_eval_builder
dataset: weather_eval
offset: 36887 # Same as _lsf_dataset.py
eval_length: 5269 # Same as _lsf_dataset.py; test_length=10539
prediction_length: ???
context_length: ???
patch_size: ???
mode: ???