_target_: uni2ts.model.multi_scale_moirai.MoiraiForecast
module:
  _target_: uni2ts.model.multi_scale_moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: Salesforce/moirai-1.0-R-base
num_samples: 100
patch_size: ???
context_length: ???
num_new_scales: 3